name: 'Terraform Plan for Azure Resources: Pay-As-You-Go'

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'subscriptions/Pay-As-You-Go/**'
  workflow_dispatch:
    inputs:
      TARGET_ENVIRONMENT:
        description: 'Target environment for deployment'
        required: true
        type: choice
        options:
          - development
          - production
        default: 'development'

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true
      TARGET_ENVIRONMENT: ${{ github.event_name == 'workflow_dispatch' && inputs.TARGET_ENVIRONMENT || (github.ref == 'refs/heads/main' && 'production' || 'development') }}
    environment: ${{ github.event_name == 'workflow_dispatch' && (inputs.TARGET_ENVIRONMENT == 'production' && 'Production' || 'Development') || (github.ref == 'refs/heads/main' && 'Production' || 'Development') }}

    defaults:
      run:
        working-directory: ./subscriptions/Pay-As-You-Go

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Login to Azure with Azure CLI'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Install Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: 'Run Terraform Init'
        run: |
          terraform init \
            -backend-config="envs/${{ env.TARGET_ENVIRONMENT }}/backend.config"

      - name: 'Run Terraform Plan'
        run: |
          terraform plan \
            -var-file="envs/${{ env.TARGET_ENVIRONMENT }}/terraform.tfvars" \
            -var="function_app_settings_additional=${{ env.TARGET_ENVIRONMENT }}"
